image:
  repository: codeberg.org/emersion/soju
  tag: "v0.10.1"

domain: irc.soap.coffee

postgresql:
  database: soju
  user: soju

admin:
  username: admin
  password: ""

resources:
  soju:
    requests:
      cpu: 10m
      memory: 32Mi
  adminSetup:
    requests:
      cpu: 10m
      memory: 32Mi

tls:
  issuer: letsencrypt
