image:
  repository: ghcr.io/continuwuity/continuwuity
  tag: "v0.5.6"

domain: m.soap.coffee
registrationToken: ""

admin:
  password: ""

storage:
  size: 5Gi

resources:
  requests:
    cpu: 50m
    memory: 256Mi
