---
apiVersion: v1
kind: Secret
metadata:
    name: postgresql
    labels:
        app.kubernetes.io/name: postgresql
type: Opaque
stringData:
    POSTGRES_HOST: postgresql:5432
    POSTGRES_USER: postgres
    POSTGRES_PASS: ENC[AES256_GCM,data:kPXz3TbRbZ3wwrj5ZyoH4CUaaRwZzO8m5YB6JI1BkKlQitOHDmrn4w==,iv:FShqMusRCS0FcO8ry2nvdJBVwDpubzkXr3Hj7iOYroE=,tag:GkjL0I6Qer3/lhCEbpPR2w==,type:str]
    POSTGRES_URI_ARGS: sslmode=disable
    POSTGRES_DEFAULT_DATABASE: postgres
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRERDNmZwVmEvSWE1UGJ4
            SGlwek1lSS9peWYzVUVjMnBUa3pEM1BDL0VjCjc4L1BGb2Rla0QydnMwTG1YTjN0
            Zmh4MlA2V25sazkyR09YT0g0RGF1NXMKLS0tIHFMenVtL21icXp6aHM2UGtBb3Fq
            UTByL0haYWExMUNPa3VTeXZ0SkRkc3MK+PPcL/bfYD/nxp7IFhWVf4A/3lUpizSW
            tcH+d1f0OBLwMhol1D7Lr0LQJYc3+LxUq3PcOloYjQYHDQgjOfFRmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kw23mavskc3ueq62mfstze85aftv5qmmd76x5x4d27tnz9rjlsasxy8fg9
    encrypted_regex: ^POSTGRES_PASS$
    lastmodified: "2026-08-31T11:42:11Z"
    mac: ENC[AES256_GCM,data:hT2YAoKqDbav2BZthLpvmloZ/qIR/yOXSdeAoIyf9Yl2mSNY54LhvnZqPe/yPUVmPlDm5qOjVHXmno9oqCSj/+GuSGYlzKDggI+aN1aUY1zBEiu01jNpKMZCRc0AvlkNTg48pW7NIMCkIykHVzB+CqRBotCG+aQL2pMzsCBXnaY=,iv:T4T9y657SyspuI0lawSxviVxkmblPxPMfBkzaRgsrVU=,tag:IvrO+F+HHw4+maNakVDJ7g==,type:str]
    version: 3.13.3
