apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bots
spec:
  interval: 10m
  timeout: 20m
  releaseName: bots
  chartRef:
    kind: OCIRepository
    name: mediawiki
  values:
    id: bots
    title: Brains on the shelf
    hostname: bots.xmu.mx
    database:
      name: mediawiki
    appSecret: mediawiki-app
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mediawiki
spec:
  interval: 10m
  url: oci://ghcr.io/lthms/raya-mediawiki/charts/mediawiki
  ref:
    # 0.0.0-dev.17.1.g3c683e471dcc
    digest: sha256:91f31c834e7010eb063d34b7c3bf57b00b271f27e4fc3ca04505078cf11d1a8c
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
