apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bots
spec:
  interval: 10m
  timeout: 20m
  releaseName: bots
  chartRef:
    kind: OCIRepository
    name: mediawiki
  values:
    id: bots
    title: Brains on the shelf
    hostname: bots.xmu.mx
    database:
      name: mediawiki
    appSecret: mediawiki-app
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mediawiki
spec:
  interval: 10m
  url: oci://ghcr.io/lthms/raya-mediawiki/charts/mediawiki
  ref:
    # 0.0.0-dev.9.1.g788abcd188d7
    digest: sha256:64c3a5de41692dcdd4eae4dbb7bc26b817c1c1bd37c526faad816bfecc445b81
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
