apiVersion: v1
kind: Secret
metadata:
    name: mediawiki-app
type: Opaque
stringData:
    MW_ADMIN_NAME: ENC[AES256_GCM,data:gTukd5g=,iv:Od5p4tXwvsJv6ph9Qb8kdwrjufsADkunejl6SEqmlRg=,tag:0KN0q4eJb++CuHYyqk8UTg==,type:str]
    MW_ADMIN_PASSWORD: ENC[AES256_GCM,data:vOAXtsKc4gZPcqhXok4f,iv:Ckr7Qa44m5pcvH+8Lry1AuY0AJu25Y4c61VeeTA34ao=,tag:w0+a6Ss5TUk6fb+FJTPLfg==,type:str]
    MW_SECRET_KEY: ENC[AES256_GCM,data:KaX/zYi5gNw9AyCX9cW3j0acOPeI1Q0TmGfmx+szhaB+sIiXL3kRfG/iJaYxuy98Itqw7lCxbfNJ8GiK284Gmg==,iv:j2+vAJXB/FaT/uxbx2Ey1U0tP9ufjjs/niB4sc0EqRg=,tag:IVsloEEbmUCWfdi99euP+g==,type:str]
    MW_UPGRADE_KEY: ENC[AES256_GCM,data:xBXBVrOPOUxR7paZPM9RjuBB9w0KGkjF5m+w9RUOAiejGc13RHdrq9WYe0OAz4Iro/F3k+66tZBJz4a8yoN+lA==,iv:ftnWgLWIAgH8XtcU/FiEImJFtMxIQ+0faLcyIucBP1g=,tag:nHxKSzhispZgi3X0r4Ha0w==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    gcp_kms:
        - created_at: "2026-09-19T13:41:37Z"
          enc: CiQAXZOUpcev0a6XxurhPgjmpG4sTJ0x9zmAw6BFij1Ew/9ynJYSSQCGHyGMWbf0QZJPQ4lG+CDqUjgIu+TpQKSPwhJ3Lk1EoxXqQmG3P0FZhRUHWqc84mTj9na2s6h0s0Nr9N0VLYYyPsGrLIuY4l8=
          resource_id: projects/raya-dns/locations/europe-west4/keyRings/raya-sops/cryptoKeys/sops
    lastmodified: "2026-09-19T13:41:38Z"
    mac: ENC[AES256_GCM,data:nNaFy8Fqd6aXQg1AQTnySEue+UXo3iJeDCXyLG/YPOs31ICeZ9iKNDR3dzlAAYBNu03GpA4h0wSYO4vvYmVqKDwZwonYBpQuhGh1si6h74hGk3++97mDzf6HvYXQBdvV7nRkiy6vW67PeyV3ATrdilNs421ARjbsQai5SA1dmKw=,iv:aPBfSW8d0tP1/xMVeWXjNVOJoq3jyT7XiD0v1CdmFRQ=,tag:vBUgKOqroXNL7DsAVKtHJA==,type:str]
    version: 3.13.3
