# The admin account Miniflux creates on first start. Read it back with
# `sops -d miniflux/secret.yaml`.
apiVersion: v1
kind: Secret
metadata:
    name: miniflux-admin
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:DciK8UvXMhnq+K1/iGDGzikWe6VGMlNl5ObI9ME2nO8=,iv:/MnAxdY9CI970v9n0bvaNnUNnNB9Q89rprvdigPQGOs=,tag:8tKOyBIuSJogHNm3t9EqLg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    gcp_kms:
        - created_at: "2026-09-13T16:05:07Z"
          enc: CiQAXZOUpRVV88KnY0fT1cNvV1ONgT3qyJW8box9UBcEJGn/9gsSSACGHyGMPzugBsY63I4xD8LT+qFoZqEH/DIuNFtx+0z0txv9ifQnsCN2N1tj7OtEFqOv1QlFkhHQwqdFIScT68ZBQVl+BWNvfA==
          resource_id: projects/raya-dns/locations/europe-west4/keyRings/raya-sops/cryptoKeys/sops
    lastmodified: "2026-09-13T16:05:07Z"
    mac: ENC[AES256_GCM,data:Bzm4hyAF5T0BJ422JCnRLNai5yN0zQfcwVswb69qKu7C8Hkl/rnczhORyZzGkEQ5LyD4j6peiw2sbM01OasJ34ORmRBkRGHkPJ81oYLSAa1fX68GmbOpjzZrRI9wwf+GEH4LbpFfpxCPIuaJ8SnSvBbnnzwD89y3C8uXev+eExM=,iv:4re7ruPKr+K+YJY0miVp4oqbCFThmKWF+QfQFwqNSFs=,tag:BChcHYep9TZ9ZnpTeKUqZQ==,type:str]
    version: 3.13.3
