# The admin account Miniflux creates on first start. Read it back with
# `sops -d miniflux/secret.yaml`.
apiVersion: v1
kind: Secret
metadata:
    name: miniflux-admin
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:JwFSZl3mmn6YuyYmR3GYyj6XIX//EXjFAqYv4+4qKKA=,iv:/MnAxdY9CI970v9n0bvaNnUNnNB9Q89rprvdigPQGOs=,tag:nJWldWdC6hJ/gc1EnZvUYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMlRpQllFcDdNTzRkTm5Z
            VC9kSXFrdU5zYnBUcU9QdEI1ZFo2Y1AyKzE0CjJUMU9aVGhhSGh5N2RqRXJsSkZZ
            Z1dxLy9xRmxld2JXbWUra2FqTzJTNXcKLS0tIGpCT0R6UC9CRGRqYWlldzUwczBv
            azg2dkQ5c1VxY0VsU1lvUWI5QlB1ZkkK8qKAKFgtrrMh82AGB4Vx2402rJ9IDr+9
            feHIinukSY9AgCfKcOz+Mw3KW/EteGqGqtrn+ang3/0f+3FcrLKg1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kw23mavskc3ueq62mfstze85aftv5qmmd76x5x4d27tnz9rjlsasxy8fg9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T12:17:02Z"
    mac: ENC[AES256_GCM,data:4wUrvotek77CSh7m/X0Pb5B8T1w8NFkTv8nW36ZeyCjSyPM1VcT4C2ccuiUe1fOKZ9hnSI4UVlFS33pMnvqRJAx5RaiCbUy1aoStRkM6/BkLirNXbiNrroHT5IlqdQvIQ71sMOX05ZTvVuzpnkfprv3GVA6X1E0Yh5Waun8onSk=,iv:6HqqxUTLhbg+rwhe1qBPMap1mBOam0XgxlCKqnGqgpI=,tag:nttoAj8oXmJOmXPnRRhK+g==,type:str]
    version: 3.13.3
