apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "garage.fullname" . }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "garage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "garage.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      enableServiceLinks: false
      containers:
        - name: garage
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 3900
              name: s3
            - containerPort: 3901
              name: rpc
            - containerPort: 3902
              name: web
            - containerPort: 3903
              name: admin
          volumeMounts:
            - name: config
              mountPath: /etc/garage.toml
              subPath: garage.toml
              readOnly: true
            - name: data
              mountPath: /var/lib/garage
      volumes:
        - name: config
          secret:
            secretName: {{ include "garage.fullname" . }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "garage.fullname" . }}
