apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage.fullname" . }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
type: Opaque
stringData:
  garage.toml: |
    metadata_dir = "/var/lib/garage/meta"
    data_dir = "/var/lib/garage/data"
    db_engine = "lmdb"
    replication_factor = 1
    compression_level = 1
    block_size = "1M"
    rpc_secret = {{ .Values.garage.rpcSecret | quote }}
    rpc_bind_addr = "[::]:3901"

    [s3_api]
    api_bind_addr = "[::]:3900"
    s3_region = {{ .Values.garage.s3Region | quote }}
    root_domain = {{ .Values.garage.webRootDomain | quote }}

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = {{ .Values.garage.webRootDomain | quote }}

    [admin]
    api_bind_addr = "0.0.0.0:3903"
    admin_token = {{ .Values.garage.adminToken | quote }}
  admin-token: {{ .Values.garage.adminToken | quote }}
  s3-access-key: {{ .Values.garage.s3AccessKey | quote }}
  s3-secret-key: {{ .Values.garage.s3SecretKey | quote }}
