apiVersion: v1
kind: Service
metadata:
  name: {{ include "garage.fullname" . }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3900
      targetPort: 3900
      name: s3
    - port: 3902
      targetPort: 3902
      name: web
    - port: 3903
      targetPort: 3903
      name: admin
  selector:
    {{- include "garage.selectorLabels" . | nindent 4 }}
