apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "n8n.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      containers:
        - name: n8n
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: N8N_HOST
              value: "0.0.0.0"
            - name: WEBHOOK_URL
              value: "https://{{ .Values.domain }}"
            - name: N8N_PROXY_HOPS
              value: "1"
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}-db-credentials
                  key: DB_POSTGRESDB_HOST
            - name: DB_POSTGRESDB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}-db-credentials
                  key: DB_POSTGRESDB_PORT
            - name: DB_POSTGRESDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}-db-credentials
                  key: DB_POSTGRESDB_DATABASE
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}-db-credentials
                  key: DB_POSTGRESDB_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}-db-credentials
                  key: DB_POSTGRESDB_PASSWORD
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}
                  key: N8N_ENCRYPTION_KEY
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 5678
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5678
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5678
