image:
  repository: docker.n8n.io/n8nio/n8n
  tag: "2.9.2"

domain: tasks.soap.coffee

postgresql:
  database: n8n
  user: n8n

encryptionKey: ""

resources:
  requests:
    cpu: 50m
    memory: 256Mi
