apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "conduwuit.fullname" . }}
  labels:
    {{- include "conduwuit.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vultr-block-storage
  resources:
    requests:
      storage: {{ .Values.storage.size }}
