apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conduwuit.fullname" . }}
  labels:
    {{- include "conduwuit.labels" . | nindent 4 }}
type: Opaque
stringData:
  registration-token: {{ .Values.registrationToken | quote }}
  admin-password: {{ .Values.admin.password | quote }}
