---
apiVersion: v1
kind: Secret
metadata:
    name: garage
type: Opaque
stringData:
    rpc-secret: ENC[AES256_GCM,data:QuaZS25JyAjpH485utnphN6qAbXVJyqXQMyQT4RniG3TuI9AWpfKHL+IKCO5faQqMNBjhBXbN4gHSeroEqKthw==,iv:Umpx71wuzkzbYvtG9DshbvY0DdPZR914DNUOdZUlYjE=,tag:p68TbUglThIUGhcvKQMXKg==,type:str]
    admin-token: ENC[AES256_GCM,data:69Av0jKVmMUsjY4jXCavIi/V8LTZqdDlUZCCi3QcxSL9+7lo+JiJGpyfPzU=,iv:b1BNwhmPpXBsVSAp4nzeQvRlVzPQQt65LETfKO/iZzA=,tag:ROQbwPmJCcg85id+XHl3gA==,type:str]
    s3-access-key: ENC[AES256_GCM,data:nQPUvKSaFXybHR+MQ6xcjaWsiK9+rRqMiVw=,iv:Ow/f6QsI9PNj1PUv2Y9Poc5ZwiV2DWd+hf27dvwebSg=,tag:FJn5qHCBGQbN7OZVr6aFIQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:qTgq3y4q0U1XrTt3i0+/Ia4aTDhxAV6PGAIJfXJivAzxJ9J64wIrEvNwu/58UL/ONw4L6kyQUOZo+7vIqzIkNQ==,iv:F9pCliqrEfLvY8VsVAiihBRxSXf5HurU+gaZb4fnCQk=,tag:wK9ia6PwmQEIY3nLAA9hVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRktycTduSnQxWHpEdTBh
            SXkxeXhWYUhJcnordE9sRjF4L2dHUFpuZUVrClJ1MkkwclB4bEdCUkdwUkt5QVpB
            dHBscUZXVjArZ2FFVTh5VlVqbWhGdTAKLS0tIHg4S1VRR2RjNDBiaTBpeUViRjNC
            S3o1OVVQTzY5SzliK3lsdC82WVp5dEEKIauMlgCVVhvCFTfCS01lR7SWyz0QLaGO
            JL+KxPiX7y+YflNdxZ433KBopd19yle7K5BFIDYPZatVh70Ll2I6rA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kw23mavskc3ueq62mfstze85aftv5qmmd76x5x4d27tnz9rjlsasxy8fg9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T11:22:47Z"
    mac: ENC[AES256_GCM,data:M6GEuCga0a5JRkVxGqQVDvueQPL0VL+TG7+s7+XlTCliCwR+aBJJIgxmS2xv4c2vzFyiBD7rnhRLXnyo2i84hBKWE5oRe+XQSLzF6eZlUuosO4RTmdKBpf5IaSz0KslgtT9l/vuWLE52xgwwfveAPO1HBXlxAseNtqLHl3YG5Ug=,iv:iQBMxbjZJ2ppMnFKh3T8W6bW8pxTUAC0t7rkM6k+oq0=,tag:S1r770ESVBrgaNFm61c9eg==,type:str]
    version: 3.13.3
