apiVersion: v1
kind: Secret
metadata:
    name: garage
type: Opaque
stringData:
    rpc-secret: ENC[AES256_GCM,data:IsQ3iNpwv4vGUhWKAxbpjSGlddTP7mZqdtXkz3UHzrQsYT8Qrrj/D7iDFr3lGVOBBymU8lxVH+Qj0ffzRjkDAg==,iv:Umpx71wuzkzbYvtG9DshbvY0DdPZR914DNUOdZUlYjE=,tag:ctkKhuJv2j5TzBiW3VXKww==,type:str]
    admin-token: ENC[AES256_GCM,data:1pmDjk3c47fOoic7APgCQzBLiCFDLW73UyKRJ30aQXi88A43zzzHM2U1flA=,iv:b1BNwhmPpXBsVSAp4nzeQvRlVzPQQt65LETfKO/iZzA=,tag:yXp3Ej3vs05mliQ2y4+EWw==,type:str]
    s3-access-key: ENC[AES256_GCM,data:UivqJ/sri8dm81FHUxyy60+LjnGqCnlEFH8=,iv:Ow/f6QsI9PNj1PUv2Y9Poc5ZwiV2DWd+hf27dvwebSg=,tag:OepNyjLCt05mk+eMk5Hnaw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:Wuf9IYv/k2C8BYL+xsijc2WglogyJNpdTfqWtMMHt77NYZWiRTzct6jU7xByMvE5zCOD+zWQ7CxFhXi7JYuPeg==,iv:F9pCliqrEfLvY8VsVAiihBRxSXf5HurU+gaZb4fnCQk=,tag:yXnrMe0A62+Iy8zcikQjFA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    gcp_kms:
        - created_at: "2026-09-13T16:05:43Z"
          enc: CiQAXZOUpQTAebA1wj9CoN6N6bh5e67J55Wy+mhMqqQ4lQsytmcSSQCGHyGMRd9Xw6WI1tL7SLUUP41BQ3HAhMptpcWRlj7iVQFw1am57RVNLddijQ0oecA8Lf9dJny1HAJ5zhWrjT5MNJ2mURv46QE=
          resource_id: projects/raya-dns/locations/europe-west4/keyRings/raya-sops/cryptoKeys/sops
    lastmodified: "2026-09-13T16:05:43Z"
    mac: ENC[AES256_GCM,data:AJniSLEk+uQ40EdhTjfi0rJixYzLPsBk1aCgFfisY3GrSsKQS4H2cj3J8MJ5FeeYVkFv7gwdVRzksfNY5YfmAV7gSinpYykaflZ9aehJU9BZPMDUDpbKN1YINXEQkPyqmNjrLAIM4RiBVsny6g2Kz+cpJLl8eIdOGtMrKj6Z17I=,iv:0FS5biqVl3sBn9EhkclcajP3WyqbprCaU35ulT0SzuA=,tag:3wfW57ifTTO8r9B9YAb0yg==,type:str]
    version: 3.13.3
